package values

type ModuleName string

const (
	Activity         ModuleName = "activity"
	Atlas            ModuleName = "atlas"
	ItemBag          ModuleName = "bag_item"
	EquipBag         ModuleName = "bag_equip"
	EquipBriefBag    ModuleName = "bag_equip_brief"
	Relics           ModuleName = "relics"
	RelicsSuit       ModuleName = "relics_suit"
	NpcTaskUnlock    ModuleName = "npc_unlock"
	User             ModuleName = "user"
	Resource         ModuleName = "resource"
	Slots            ModuleName = "slots"
	Friend           ModuleName = "friend"
	Mail             ModuleName = "mail"
	Gift             ModuleName = "gift"
	Guild            ModuleName = "guild"
	GuildApply       ModuleName = "guild_apply"
	GuildUserApply   ModuleName = "guild_user_apply"
	GuildMember      ModuleName = "guild_member"
	GuildUser        ModuleName = "guild_user"
	GuildInvite      ModuleName = "guild_invite"
	Hero             ModuleName = "hero"
	HeroBiography    ModuleName = "hero_biography"
	MapStory         ModuleName = "map_story"
	RoleAttr         ModuleName = "role_attr"
	SkillStone       ModuleName = "skill_stone"
	Gacha            ModuleName = "gacha"
	GachaUnlock      ModuleName = "gacha_unlock"
	Cond             ModuleName = "cond"
	Task             ModuleName = "task"
	TaskMapper       ModuleName = "task_mapper"
	AdvanceDungeon   ModuleName = "advance_dungeon"
	StageExplore     ModuleName = "stage_explore"
	Arena            ModuleName = "arena"
	BossHallKill     ModuleName = "boss_hall_kill"
	BossHallKillJoin ModuleName = "boss_hall_kill_Join"
	AppointMapEvent  ModuleName = "appoint_map_event"
	UpdateReward     ModuleName = "update_reward"
	TalentRune       ModuleName = "talent_rune"
	Pay              ModuleName = "pay"
	Notice           ModuleName = "notice"
)
